baseURL: https://stories.matteojoliveau.com
languageCode: en-gb
title: Stories
copyright: '{year} Matteo Joliveau.'

taxonomies:
  tag: tags
  author: authors

menu:
  main:
  - name: Contacts
    url: /contacts/

enableGitInfo: true
enableRobotsTXT: true
module:
  mounts:
    - source: ./static
      target: static
    - source: ./node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
markup:
  goldmark:
    renderer:
      unsafe: false
