base_url = "https://stories.matteojoliveau.com"
title = "Stories"
compile_sass = false
build_search_index = false
render_emoji = true
generate_feed = true

default_language = "en"

[translations]
by = "by"
nothing-here = "Uh oh, there is nothing here"
available-in = "Available in"
sections = "Sections"
pages = "Pages"
search = "Search"
back-to-quests = "Back to quests"
reading-time = "Reading time"
minutes = "minutes"
content = "Content"
general = "General"
encounters = "Encounters"
authors = "Authors"
toc = "Contents"
published = "Published"
last-updated = "Last updated"

footer_license = "Source code is released under the [ISC license](https://opensource.org/licenses/ISC) and is available on [GitHub](https://github.com/matteojoliveau/stories)"
footer_cc = """
The content of this website (any text, copy and original content, including but not limited to stories, settings, names and artworks)
is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License](https://creativecommons.org/licenses/by-nc-sa/4.0)
unless otherwise specified
"""

[languages.it]
generate_feed = true

[languages.it.translations]
by = "di"
nothing-here = "Uh oh, non c'è niente qui"
available-in = "Disponibile in"
sections = "Sezioni"
pages = "Pagine"
search = "Cerca"
back-to-quests = "Torna alle quests"
reading-time = "Tempo di lettura"
minutes = "minuti"
content = "Contenuti"
general = "Generale"
encounters = "Incontri"
authors = "Autori"
toc = "Indice"
published = "Pubblicato il"
last-updated = "Ultima modifica"

footer_license = "Codice sorgente rilasciato dietro [licenza ISC](https://opensource.org/licenses/ISC) e disponibile su [GitHub](https://github.com/matteojoliveau/stories)"
footer_cc = """
Il contenuto di questo sito (qualunque testo e altri contenuti originali, inclusi ma non limitati a storie, ambientazioni, nomi e materiale grafico)
è concesso in licenza secondo i termini della [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License](https://creativecommons.org/licenses/by-nc-sa/4.0)
se non diversamente specificato
"""

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
default_cover = "cover.jpg"
site_twitter = "matteojoliveau"
